// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	taxonomy "archdesc-apis/app/taxonomy/cmd/api/internal/handler/taxonomy"
	"archdesc-apis/app/taxonomy/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/taxonomies/info",
				Handler: taxonomy.GetTaxonomyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/taxonomies",
				Handler: taxonomy.GetAllTaxonomiesHandler(serverCtx),
			},
		},
	)
}
