// Code generated by goctl. DO NOT EDIT!
// Source: taxonomy.proto

package server

import (
	"context"

	"archdesc-apis/app/taxonomy/cmd/rpc/internal/logic"
	"archdesc-apis/app/taxonomy/cmd/rpc/internal/svc"
	"archdesc-apis/app/taxonomy/cmd/rpc/pb/taxonomy"
)

type TaxonomiesServer struct {
	svcCtx *svc.ServiceContext
	taxonomy.UnimplementedTaxonomiesServer
}

func NewTaxonomiesServer(svcCtx *svc.ServiceContext) *TaxonomiesServer {
	return &TaxonomiesServer{
		svcCtx: svcCtx,
	}
}

func (s *TaxonomiesServer) Get(ctx context.Context, in *taxonomy.ReqTaxonomyId) (*taxonomy.Taxonomy, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}

func (s *TaxonomiesServer) GetAll(ctx context.Context, in *taxonomy.ReqGetAll) (*taxonomy.RespGetAll, error) {
	l := logic.NewGetAllLogic(ctx, s.svcCtx)
	return l.GetAll(in)
}
