// Code generated by goctl. DO NOT EDIT!
// Source: taxonomyservice.proto

package server

import (
	"context"

	"archdesc-apis/app/taxonomy/cmd/rpc/internal/logic"
	"archdesc-apis/app/taxonomy/cmd/rpc/internal/svc"
	"archdesc-apis/app/taxonomy/cmd/rpc/pb/taxonomyservice"
)

type TaxonomyServiceServer struct {
	svcCtx *svc.ServiceContext
	taxonomyservice.UnimplementedTaxonomyServiceServer
}

func NewTaxonomyServiceServer(svcCtx *svc.ServiceContext) *TaxonomyServiceServer {
	return &TaxonomyServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TaxonomyServiceServer) Get(ctx context.Context, in *taxonomyservice.ReqTaxonomyId) (*taxonomyservice.Taxonomy, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}

func (s *TaxonomyServiceServer) GetAll(ctx context.Context, in *taxonomyservice.ReqGetAll) (*taxonomyservice.RespGetAll, error) {
	l := logic.NewGetAllLogic(ctx, s.svcCtx)
	return l.GetAll(in)
}
