// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	taxonomyFieldNames          = builder.RawFieldNames(&Taxonomy{})
	taxonomyRows                = strings.Join(taxonomyFieldNames, ",")
	taxonomyRowsExpectAutoSet   = strings.Join(stringx.Remove(taxonomyFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	taxonomyRowsWithPlaceHolder = strings.Join(stringx.Remove(taxonomyFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	taxonomyModel interface {
		Insert(ctx context.Context, data *Taxonomy) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Taxonomy, error)
		Update(ctx context.Context, data *Taxonomy) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTaxonomyModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Taxonomy struct {
		Id            int64          `db:"id"`
		Usage         sql.NullString `db:"usage"`
		ParentId      sql.NullInt64  `db:"parent_id"`
		SourceCulture string         `db:"source_culture"`
	}
)

func newTaxonomyModel(conn sqlx.SqlConn) *defaultTaxonomyModel {
	return &defaultTaxonomyModel{
		conn:  conn,
		table: "`taxonomy`",
	}
}

func (m *defaultTaxonomyModel) Insert(ctx context.Context, data *Taxonomy) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, taxonomyRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Usage, data.ParentId, data.SourceCulture)
	return ret, err
}

func (m *defaultTaxonomyModel) FindOne(ctx context.Context, id int64) (*Taxonomy, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", taxonomyRows, m.table)
	var resp Taxonomy
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaxonomyModel) Update(ctx context.Context, data *Taxonomy) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, taxonomyRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Usage, data.ParentId, data.SourceCulture, data.Id)
	return err
}

func (m *defaultTaxonomyModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTaxonomyModel) tableName() string {
	return m.table
}
