// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	taxonomyI18nFieldNames          = builder.RawFieldNames(&TaxonomyI18n{})
	taxonomyI18nRows                = strings.Join(taxonomyI18nFieldNames, ",")
	taxonomyI18nRowsExpectAutoSet   = strings.Join(stringx.Remove(taxonomyI18nFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	taxonomyI18nRowsWithPlaceHolder = strings.Join(stringx.Remove(taxonomyI18nFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	taxonomyI18nModel interface {
		Insert(ctx context.Context, data *TaxonomyI18n) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TaxonomyI18n, error)
		Update(ctx context.Context, data *TaxonomyI18n) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTaxonomyI18nModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TaxonomyI18n struct {
		Name    sql.NullString `db:"name"`
		Note    sql.NullString `db:"note"`
		Id      int64          `db:"id"`
		Culture string         `db:"culture"`
	}
)

func newTaxonomyI18nModel(conn sqlx.SqlConn) *defaultTaxonomyI18nModel {
	return &defaultTaxonomyI18nModel{
		conn:  conn,
		table: "`taxonomy_i18n`",
	}
}

func (m *defaultTaxonomyI18nModel) Insert(ctx context.Context, data *TaxonomyI18n) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, taxonomyI18nRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Note, data.Culture)
	return ret, err
}

func (m *defaultTaxonomyI18nModel) FindOne(ctx context.Context, id int64) (*TaxonomyI18n, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", taxonomyI18nRows, m.table)
	var resp TaxonomyI18n
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaxonomyI18nModel) Update(ctx context.Context, data *TaxonomyI18n) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, taxonomyI18nRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Note, data.Culture, data.Id)
	return err
}

func (m *defaultTaxonomyI18nModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTaxonomyI18nModel) tableName() string {
	return m.table
}
