// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
}

type Response struct {
}

type ReqTaxonomyId struct {
	Id int64 `json:"id"`
}

type Taxonomy struct {
	Id   int64  `json:"id"`
	Term string `json:"term"`
}
